spring:
  output:
    ansi:
      enabled: always
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  jmx:
    enabled: false

logging:
  level:
    com:
      scarlatti:
        ise: DEBUG